# Generated by Django 5.1.6 on 2025-02-20 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
